### ISSUE TITLE
[Feature Requst] Add hotkey

### ISSUE THREAD

**Issue by supersaiyansubtlety** [abigailfails/HelpfulHitboxes#1]
It would be great to have a hotkey to activate helpful hitboxes. 

Having two, one to toggle and one to hold would be even better. 

Currently you can't bridge out on panes and fences because when standing on top of them, you can't reach the side of them. 

I also think it might be worth adding a setting to give full hitboxes to all blocks if you add hotkeys, since you'd only turn them on when you want them anyways.

**Comment by solarsonata** [comment]
Thanks for bringing this up, I'll have to think about this.

**Comment by solarsonata** [comment]
I've implemented the hotkey, but I'm having trouble getting every block to use a full hitbox; how much do you want that option? :p

**Comment by supersaiyansubtlety** [comment]
It's not important, just the hotkey would be great : ]

**Comment by solarsonata** [comment]
I forgot to close this, the hotkey was added in an update a while ago.
